version: "3"

services:

  mongo:
    image: mongo:6.0.9
    container_name: mongo
    restart: always
    volumes:
    - ./ops/mongo.conf:/etc/mongo.conf
    - /data/go-bookmarks/mongodb:/data/db

  api:
    build: .
    container_name: api
    restart: always
    environment:
      PORT: 4070
      MONGO_URL: mongo/bookmarks
    ports:
    - "4070:4070"
    depends_on:
    - mongo