version: "3"

services:

  mongo:
    image: mongo:3.4.9
    container_name: mongo
    restart: always
    ports:
    - "27017:27017"
    volumes:
    - ./ops/mongo.conf:/etc/mongo.conf
    - /data/go-bookmarks/mongodb:/data/db

  api:
    build: .
    container_name: api
    restart: always
    ports:
    - "4070:4070"
    depends_on:
    - mongo